services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_apache_php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
